media:
  input: public/images
  output: /images

content:
  - name: letters
    label: Letters
    type: collection
    path: src/content/letters
    fields:
      - name: title
        type: string
        label: Title
        required: true
        hint: "A compelling title for the letter"
      - name: author
        type: object
        label: Author
        fields:
          - name: name
            type: string
            label: Name
            required: true
          - name: birth_year
            type: number
            label: Birth Year
          - name: death_year
            type: number
            label: Death Year
          - name: bio
            type: text
            label: Biography
            hint: "Brief description of the author"
      - name: recipient
        type: string
        label: Recipient
        required: true
        hint: "Who received this letter"
      - name: date
        type: date
        label: Date
        required: true
      - name: context
        type: string
        label: Context
        required: true
        hint: "Brief context for display (e.g., 'To Vita Sackville-West, January 1927')"
      - name: location
        type: string
        label: Location
        hint: "Where the letter was written"
      - name: excerpt
        type: text
        label: Excerpt
        required: true
        hint: "First 1-2 sentences for preview"
      - name: signature
        type: string
        label: Signature
        hint: "How the letter was signed"
      - name: source
        type: string
        label: Source
        required: true
        hint: "Citation for the letter source"
      - name: collections
        type: array
        label: Collections
        items:
          type: string
        hint: "Thematic collections this belongs to"
      - name: tags
        type: array
        label: Tags
        items:
          type: string
        hint: "Descriptive tags"
      - name: featured
        type: boolean
        label: Featured
        default: false
        hint: "Show on homepage"
      - name: drop_cap_color
        type: select
        label: Drop Cap Color
        options:
          - value: "#e07a5f"
            label: "Coral"
          - value: "#81b29a"
            label: "Sage Green"
          - value: "#f2cc8f"
            label: "Golden Yellow"
          - value: "#9381c2"
            label: "Lavender"
          - value: "#f07167"
            label: "Soft Red"
        default: "#e07a5f"
      - name: about
        type: object
        label: About This Letter
        collapsed: true
        fields:
          - name: context
            type: markdown
            label: Historical Context
            hint: "Background about when/why this was written"
          - name: significance
            type: markdown
            label: Significance
            hint: "Why this letter is important"
          - name: author_bio
            type: markdown
            label: About the Author
            hint: "Biographical information"
          - name: recipient_info
            type: markdown
            label: About the Recipient
            hint: "Information about who received this"
          - name: links
            type: array
            label: Additional Resources
            items:
              type: object
              fields:
                - name: title
                  type: string
                  label: Link Title
                  required: true
                - name: url
                  type: string
                  label: URL
                - name: description
                  type: string
                  label: Description
      - name: body
        type: markdown
        label: Letter Content
        required: true
        hint: "Full text of the letter"

  - name: speeches
    label: Speeches
    type: collection
    path: src/content/speeches
    fields:
      - name: title
        type: string
        label: Title
        required: true
      - name: author
        type: object
        label: Author
        fields:
          - name: name
            type: string
            label: Name
            required: true
          - name: birth_year
            type: number
            label: Birth Year
          - name: death_year
            type: number
            label: Death Year
          - name: bio
            type: text
            label: Biography
      - name: date
        type: date
        label: Date
        required: true
      - name: context
        type: string
        label: Context
        required: true
      - name: location
        type: string
        label: Location
      - name: occasion
        type: string
        label: Occasion
        hint: "Event or reason for the speech"
      - name: excerpt
        type: text
        label: Excerpt
        required: true
        hint: "Opening lines for preview"
      - name: source
        type: string
        label: Source
        required: true
      - name: collections
        type: array
        label: Collections
        items:
          type: string
      - name: tags
        type: array
        label: Tags
        items:
          type: string
      - name: featured
        type: boolean
        label: Featured
        default: false
      - name: drop_cap_color
        type: select
        label: Drop Cap Color
        options:
          - value: "#e07a5f"
            label: "Coral"
          - value: "#81b29a"
            label: "Sage Green"
          - value: "#f2cc8f"
            label: "Golden Yellow"
          - value: "#9381c2"
            label: "Lavender"
          - value: "#f07167"
            label: "Soft Red"
        default: "#e07a5f"
      - name: body
        type: markdown
        label: Speech Content
        required: true

  - name: garden
    label: Garden
    type: collection
    path: src/content/garden
    fields:
      - name: title
        type: string
        label: Title
        required: true
        hint: "Brief title for this entry"
      - name: type
        type: select
        label: Type
        required: true
        options:
          - value: thoughts
            label: "💭 Thoughts"
          - value: links
            label: "🔗 Links"
          - value: quotes
            label: "💬 Quotes"
          - value: notes
            label: "📝 Notes"
        default: thoughts
      - name: date
        type: datetime
        label: Date
        required: true
      - name: content
        type: text
        label: Content
        required: true
        hint: "The main content of this entry"
      - name: tags
        type: array
        label: Tags
        items:
          type: string
        hint: "Simple tags for organization"
      - name: featured
        type: boolean
        label: Featured
        default: false
      # Quote-specific fields
      - name: attribution
        type: string
        label: Attribution
        hint: "For quotes - who said this?"
        condition:
          field: type
          value: quotes
      - name: author
        type: string
        label: Author
        hint: "Author name (for quotes)"
        condition:
          field: type
          value: quotes
      - name: source
        type: string
        label: Source
        hint: "Source reference"
        condition:
          field: type
          value: quotes
      # Link-specific fields
      - name: link
        type: object
        label: Link Details
        condition:
          field: type
          value: links
        fields:
          - name: title
            type: string
            label: Link Title
            required: true
          - name: url
            type: string
            label: URL
            required: true
          - name: domain
            type: string
            label: Domain
            hint: "e.g., example.com (auto-extracted from URL)"
          - name: preview
            type: text
            label: Preview
            hint: "Brief description of the link (optional)"
      - name: private
        type: boolean
        label: Private
        default: false
        hint: "Keep this entry private (not displayed publicly)"

  - name: essays
    label: Essays
    type: collection
    path: src/content/essays
    fields:
      - name: title
        type: string
        label: Title
        required: true
      - name: author
        type: object
        label: Author
        fields:
          - name: name
            type: string
            label: Name
            required: true
          - name: birth_year
            type: number
            label: Birth Year
          - name: death_year
            type: number
            label: Death Year
          - name: description
            type: text
            label: Description
            hint: "Brief author description (note: some essays use 'description' instead of 'bio')"
      - name: date
        type: date
        label: Date
        required: true
      - name: context
        type: string
        label: Context
        required: true
        hint: "Publication context and background"
      - name: source
        type: string
        label: Source
        required: true
      - name: source_url
        type: string
        label: Source URL
        hint: "Direct link to source (if available)"
      - name: excerpt
        type: text
        label: Excerpt
        required: true
        hint: "Opening lines for preview"
      - name: tags
        type: array
        label: Tags
        items:
          type: string
      - name: featured
        type: boolean
        label: Featured
        default: false
      - name: drop_cap_color
        type: select
        label: Drop Cap Color
        options:
          - value: "#e07a5f"
            label: "Coral"
          - value: "#81b29a"
            label: "Sage Green"
          - value: "#f2cc8f"
            label: "Golden Yellow"
          - value: "#9381c2"
            label: "Lavender"
          - value: "#f07167"
            label: "Soft Red"
          - value: "#8B4513"
            label: "Saddle Brown"
        default: "#e07a5f"
      - name: body
        type: markdown
        label: Essay Content
        required: true

  - name: lectures
    label: Lectures
    type: collection
    path: src/content/lectures
    fields:
      - name: title
        type: string
        label: Title
        required: true
      - name: author
        type: object
        label: Author
        fields:
          - name: name
            type: string
            label: Name
            required: true
          - name: birth_year
            type: number
            label: Birth Year
          - name: death_year
            type: number
            label: Death Year
          - name: bio
            type: text
            label: Biography
      - name: date
        type: date
        label: Date
        required: true
      - name: context
        type: string
        label: Context
        required: true
      - name: location
        type: string
        label: Location
      - name: institution
        type: string
        label: Institution
      - name: series
        type: string
        label: Lecture Series
      - name: lecture_number
        type: number
        label: Lecture Number
      - name: excerpt
        type: text
        label: Excerpt
        required: true
      - name: source
        type: string
        label: Source
        required: true
      - name: collections
        type: array
        label: Collections
        items:
          type: string
      - name: tags
        type: array
        label: Tags
        items:
          type: string
      - name: featured
        type: boolean
        label: Featured
        default: false
      - name: drop_cap_color
        type: select
        label: Drop Cap Color
        options:
          - value: "#e07a5f"
            label: "Coral"
          - value: "#81b29a"
            label: "Sage Green"
          - value: "#f2cc8f"
            label: "Golden Yellow"
          - value: "#9381c2"
            label: "Lavender"
          - value: "#f07167"
            label: "Soft Red"
          - value: "#9370DB"
            label: "Medium Purple"
        default: "#e07a5f"
      - name: about
        type: object
        label: About This Lecture
        collapsed: true
        fields:
          - name: context
            type: markdown
            label: Historical Context
          - name: significance
            type: markdown
            label: Significance
          - name: author_bio
            type: markdown
            label: About the Author
          - name: series_info
            type: markdown
            label: Series Information
          - name: links
            type: array
            label: Additional Resources
            items:
              type: object
              fields:
                - name: title
                  type: string
                  label: Link Title
                  required: true
                - name: url
                  type: string
                  label: URL
                - name: description
                  type: string
                  label: Description
      - name: body
        type: markdown
        label: Lecture Content
        required: true

  - name: collections
    label: Collections
    type: collection
    path: src/content/collections
    fields:
      - name: name
        type: string
        label: Collection Name
        required: true
      - name: slug
        type: string
        label: Slug
        required: true
        hint: "URL-friendly version (e.g., love-letters, wartime-correspondence)"
      - name: description
        type: text
        label: Description
        required: true
      - name: color
        type: color
        label: Theme Color
        default: "#d4a574"
      - name: body
        type: markdown
        label: Collection Description
        hint: "Extended description (optional)"